### ISSUE TITLE
run the project

### ISSUE THREAD

**Issue by jenong-140** [Devjeel/Heart_Disease_KNN_Model#2]
how to run this program :( i was dumb bro help, and thanks

**Comment by Devjeel** [comment]
Find more on how to run project from README [here](https://github.com/Devjeel/Heart_Disease_KNN_Model/blob/master/README.md#to-run-this-code-on-your-machine)

Update POST request to send your JSON data from [here](https://github.com/Devjeel/Heart_Disease_KNN_Model/blob/b2b4bce77d57adaebfc75cdc8a33ca526ab08309/request.py#L10)

NOTE: you might need to update the URL to your running flask server [here](https://github.com/Devjeel/Heart_Disease_KNN_Model/blob/b2b4bce77d57adaebfc75cdc8a33ca526ab08309/request.py#L8)
